package kr.junhyung.mcagents.botfabric.tool;

import static java.util.Map.entry;

import java.util.Map;

/**
 * Generated by hack/sync-catalog.py from mcp-server's catalog.json. Do not edit by hand.
 *
 * <p>Catalogue version 3.11.0.
 *
 * <p>The hash a bot reports has to come from the catalogue rather than from the bot's own opinion
 * of the schema, or it agrees with nothing but itself. A tool with no entry here has nothing to
 * agree with, so it is not offered.
 */
public final class CatalogHashes {

    public static final String CATALOG_VERSION = "3.11.0";

    private static final Map<String, String> BY_TOOL = Map.ofEntries(
            entry("activate-block", "sha256:745bc34ffa94b53097b81ff9cabd6d41db733664935cd5c7d7a9a090cc329c65"),
            entry("attack-entity", "sha256:ad34f9f2602d72747786a2ad0758c1debc3e06367a46ff110d04dd4636edd27a"),
            entry("can-craft", "sha256:ff3fc389c507c53b6579cb9f27e960030ff0819170a6554d70c117b705d10fc6"),
            entry("click-chat", "sha256:129f1a323b4b58b410c8e4ae2857cf7c63294809cead493121856292daaf4a89"),
            entry("click-slot", "sha256:e73d8185908341ecc5ec628d7447dc888db0d4753fa468983a53b05c659a0af7"),
            entry("close-window", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("complete-command", "sha256:937b4b843b9e6bec05bff52a534955be179725d519c0836dab5568e0e47428d8"),
            entry("craft-item", "sha256:6eabdd8f7377be1796b386f6580f7b9d6d26e94007e165598a78f628b45d1545"),
            entry("dig-block", "sha256:745bc34ffa94b53097b81ff9cabd6d41db733664935cd5c7d7a9a090cc329c65"),
            entry("drag-slots", "sha256:070f5bff43a38bd50f828b7577c9c1f19f685436a95291782fac2304b200fcf1"),
            entry("drop-held-item", "sha256:75939f2efaf6239b49c458120d06cea9f954bfeecb0716a73ef98feb7f1c4c4f"),
            entry("equip-item", "sha256:27acd4f5ec4c5f8b1d7a0b68b4815c4d5df3d56b5ad6948ed5bcbd274fcfbd8b"),
            entry("find-blocks", "sha256:09b6e3f01aaf0deb82deb37931f322029cc1a3d074fc3bf78c7272ce393efe8a"),
            entry("find-entity", "sha256:edc4079f23fb94f5260a9eebdfaa77b5fa60522c056205b3cbd1af9b687e73d0"),
            entry("find-item", "sha256:03d628f9c594f99d125da58edc5215819cf61b5d2aad8102f42aab19de171135"),
            entry("fish", "sha256:264d959167057c7b4e46bcdaaf6a2a15d99a2807fa3abcf953ab4c85a21b6406"),
            entry("fly-to", "sha256:745bc34ffa94b53097b81ff9cabd6d41db733664935cd5c7d7a9a090cc329c65"),
            entry("get-block-info", "sha256:745bc34ffa94b53097b81ff9cabd6d41db733664935cd5c7d7a9a090cc329c65"),
            entry("get-player-state", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("get-position", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("get-recipe", "sha256:43b6fd98f5f3aaa4d775078049aff85984616425cadbc9b90cd94485753d8645"),
            entry("get-target-block", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("get-world-state", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("give-item", "sha256:53f2f7218c621e697a8255ddfc89d4ee5bf1bfcc803e70b31e40cb93a5b5840d"),
            entry("interact-entity", "sha256:34e1bc55c70e5bfb98e332cfb17c3ebecf6c0e115a101c51e7de4662a7342504"),
            entry("jump", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("list-inventory", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("list-recipes", "sha256:3f3167d3a8a4e89e377b172a705c77bd7f02c491abb7a32c289d33f92a7408cb"),
            entry("look-at", "sha256:745bc34ffa94b53097b81ff9cabd6d41db733664935cd5c7d7a9a090cc329c65"),
            entry("move-in-direction", "sha256:0c94cab2eaa38162b31a6c28dd29b7bf7bb8e2531551c34b0d6c7ac65573310d"),
            entry("move-to-position", "sha256:7b260e17f8c3524018ab301c032da4040a02a7285580f7c6895c90ec0d07dcca"),
            entry("open-container", "sha256:745bc34ffa94b53097b81ff9cabd6d41db733664935cd5c7d7a9a090cc329c65"),
            entry("open-inventory", "sha256:9f4bd22029a76816a5adf4d36f944683f85eb4d664e8ace73e1e42c706013b0f"),
            entry("place-block", "sha256:1d8ac28736965a5135225168273bdababada6360c320eed181f50e766f6d5797"),
            entry("press-container-button", "sha256:d7d1b6d413cf434807e2697461b939f43f9e1a268472d271c3b75ef988d6ae11"),
            entry("press-dialog-button", "sha256:1010547a2695089153ad40d50abaa241830dddac1a875129be6cb7b41961789a"),
            entry("read-advancements", "sha256:a13a1bc55bd4bef96319e778f70a981fbbd4ef5e7d268be0bcb787a4d55f8483"),
            entry("read-block-entity", "sha256:745bc34ffa94b53097b81ff9cabd6d41db733664935cd5c7d7a9a090cc329c65"),
            entry("read-book", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("read-boss-bars", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("read-container-options", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("read-displays", "sha256:b3e9baab003ac5f71d20062769363d14c389eaf32bcdc178262699127f884afb"),
            entry("read-player-list", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("read-scoreboard", "sha256:4fb4263637a58cb79437f6cee058c25c99acbe77297b9f5bfd22f8af5863b2b4"),
            entry("read-trades", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("read-window", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("respawn", "sha256:d746974fa9afd5e951f76f9af38954b0ad7f436f2120dc974da65e5ee39f856f"),
            entry("run-command", "sha256:878128a98ab0f67dffb8ea8fedd3b7cf732ef549f4a814fed57c7348906b55d7"),
            entry("screenshot", "sha256:5e168363ead5955da20ee091a62d2d24a085a14ca43f7c52479b2a3655e40465"),
            entry("select-trade", "sha256:dca18d169df2b97eead79c37bf85bd55ac217323864fc9fcc3d2563cd3ed2bc0"),
            entry("send-chat", "sha256:5c7dd5f9ce17e6ef4722a41c75a474b6dddbbccab91d61afb2ada4ef8ff46829"),
            entry("set-stance", "sha256:f2f7d5bf9fae762bd098393230fd01c27e1a6f1ef5b03851883addb71161ed20"),
            entry("smelt-item", "sha256:ee0fe9d676a496f246a7677f80dc3969187e96e741d3b20c67b24a651b55cfa5"),
            entry("switch-server", "sha256:00d3e77dd497e1df245c1cdcdd76472db66e5cb0e54f8989559990cbdf3340b5"),
            entry("type-text", "sha256:0e9e7b2062965b2f74886dc72714f8c7f1e9669e89095061ca988d5720dc25d0"),
            entry("use-held-item", "sha256:be71408a791259c0ae552a277f45f615cc325b030818c35a16b91fc042505a26"),
            entry("wait-for-window", "sha256:b20d676b0fdbcb821a1bf4d695a50f8fcd46618b37b642f323fd81e839671b3d"),
            entry("wait-ticks", "sha256:b2835c343bcf281db2c56d1f1b5c3a25624f0d7d0ce68425286991b7d70d55ec"));

    private CatalogHashes() {
    }

    public static String of(String tool) {
        String hash = BY_TOOL.get(tool);
        if (hash == null) {
            throw new IllegalStateException(
                    tool + " has no hash in the catalogue; run hack/sync-catalog.py");
        }
        return hash;
    }
}
