#!/usr/bin/env python3
"""Copy the argument hashes out of mcp-server's catalogue into CatalogHashes.java.

The catalogue belongs to mcp-server: it owns the argument schemas, so it owns their hashes. This
bot only has to agree, and a hash it made up would agree with nothing but itself.

Each tool used to carry its hash as a literal in its own class, which meant a catalogue change
disabled that tool at the next handshake and nothing here said so. Generating one file makes the
change a diff to review.

    hack/sync-catalog.py [path to catalog.json]
"""

import hashlib
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
DEFAULT = REPO.parent / "mcp-server/catalog/catalog.json"
TARGET = REPO / "src/main/java/kr/junhyung/mcagents/botfabric/tool/CatalogHashes.java"
KIND = "fabric"

# A composed tool is half a bot call and half something mcp-server does with its own buffers, so
# the bot implements it like any other.
ROUTES_A_BOT_ANSWERS = {"rpc", "compose"}


def canonical(value):
    if isinstance(value, dict):
        return {key: canonical(value[key]) for key in sorted(value)}
    if isinstance(value, list):
        return [canonical(item) for item in value]
    return value


def digest(value):
    encoded = json.dumps(canonical(value), separators=(",", ":"), ensure_ascii=False).encode()
    return "sha256:" + hashlib.sha256(encoded).hexdigest()


source = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT
catalog = json.loads(source.read_text())

mine = sorted(
    # A tool with no wire schema sends a bot nothing of its own: a wait polls another tool, and
    # that one is what crosses the wire. Reporting it as a capability would offer something this
    # mod has no handler for.
    (tool for tool in catalog["tools"]
     if tool["route"] in ROUTES_A_BOT_ANSWERS and KIND in tool["kinds"] and tool.get("wireSchema")),
    key=lambda tool: tool["name"],
)

for tool in mine:
    stored = tool.get("wireSchemaHash")
    computed = digest(tool["wireSchema"])
    if stored != computed:
        raise SystemExit(
            "%s: the catalogue's own hash does not describe its schema (%s vs %s)"
            % (tool["name"], stored, computed))

entries = "\n".join(
    '            entry("%s", "%s"),' % (tool["name"], tool["wireSchemaHash"]) for tool in mine
).rstrip(",")

TARGET.write_text('''package kr.junhyung.mcagents.botfabric.tool;

import static java.util.Map.entry;

import java.util.Map;

/**
 * Generated by hack/sync-catalog.py from mcp-server's catalog.json. Do not edit by hand.
 *
 * <p>Catalogue version %s.
 *
 * <p>The hash a bot reports has to come from the catalogue rather than from the bot's own opinion
 * of the schema, or it agrees with nothing but itself. A tool with no entry here has nothing to
 * agree with, so it is not offered.
 */
public final class CatalogHashes {

    public static final String CATALOG_VERSION = "%s";

    private static final Map<String, String> BY_TOOL = Map.ofEntries(
%s);

    private CatalogHashes() {
    }

    public static String of(String tool) {
        String hash = BY_TOOL.get(tool);
        if (hash == null) {
            throw new IllegalStateException(
                    tool + " has no hash in the catalogue; run hack/sync-catalog.py");
        }
        return hash;
    }
}
''' % (catalog["catalogVersion"], catalog["catalogVersion"], entries))

print("%s: %d %s tools from catalogue %s"
      % (TARGET.relative_to(REPO), len(mine), KIND, catalog["catalogVersion"]))
